version: '3.9'

services:

  frontendbook:
      build:
        context: ./FrontendBook
        dockerfile: ./Dockerfile
      ports:
        - "9081:8080"
      depends_on:
        - postgres
      environment:
        - ASPNETCORE_ENVIRONMENT=Docker

  apibook:
      build:
        context: ./ApiBookTest
        dockerfile: ./Dockerfile
      ports:
        - "9080:8080"
      depends_on:
        - postgres
      environment:
        - ASPNETCORE_ENVIRONMENT=Docker

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: enter12345
      POSTGRES_DB: BDBookTest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./Postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

volumes:
  db-data: