// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ApiBookTest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace ApiBookTest.Models.Configurations
{
    public partial class authorsConfiguration : IEntityTypeConfiguration<authors>
    {
        public void Configure(EntityTypeBuilder<authors> entity)
        {
            entity.HasKey(e => e.id).HasName("authors_pkey");

            entity.Property(e => e.name).HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<authors> entity);
    }
}
